version = 1
disable_existing_loggers = true

[formatters.default]
class = "logging.Formatter"
datefmt = "%Y-%m-%d %H:%M:%S"
tzname = "Asia/Seoul"
format = "%(asctime)-s - %(name)-15s - %(levelname)-8s - %(message)s"

[formatters.debug]
class = "logging.Formatter"
datefmt = "%Y-%m-%d %H:%M:%S"
format = "%(asctime)-s - %(name)-15s - %(levelname)-8s - %(funcName)s - %(message)s"

[handlers.console]
class = "logging.StreamHandler"
level = "INFO"
formatter = "default"
stream = "ext://sys.stdout"

[handlers.info_file_handler]
class = "logging.handlers.RotatingFileHandler"
level = "INFO"
formatter = "default"
filename = "./tmp/info.log"
maxBytes = 10485760
backupCount = 20
encoding = "utf8"

[handlers.error_file_handler]
class = "logging.handlers.RotatingFileHandler"
level = "ERROR"
formatter = "debug"
filename = "./tmp/errors.log"
maxBytes = 10485760
backupCount = 20
encoding = "utf8"

[handlers.debug_file_handler]
class = "logging.handlers.RotatingFileHandler"
level = "DEBUG"
formatter = "debug"
filename = "./tmp/debug.log"
maxBytes = 10485760
backupCount = 20
encoding = "utf8"

[handlers.critical_file_handler]
class = "logging.handlers.RotatingFileHandler"
level = "CRITICAL"
formatter = "debug"
filename = "./tmp/critical.log"
maxBytes = 10485760
backupCount = 20
encoding = "utf8"

[handlers.warn_file_handler]
class = "logging.handlers.RotatingFileHandler"
level = "WARN"
formatter = "debug"
filename = "./tmp/warn.log"
maxBytes = 10485760
backupCount = 20
encoding = "utf8"

[loggers.tests]
level = "INFO"
handlers = [
    "console",
]

[root]
level = "DEBUG"
handlers = [
    "console",
    "info_file_handler",
    "debug_file_handler",
]
