name: Python CI/CD

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/second-ci.yaml"
      - "second-ci/**"

env:
  PACKAGE: practice
  PROJECT_DIR: my-ci

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  build:
    runs-on: ubuntu-latest
    needs:
      - test
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2